apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitops
  namespace: gitops-ns
spec:
  releaseName: gitops
  chart:
    spec:
      chart: charts/gitops
      version: "0.0.1"
      sourceRef:
        kind: GitRepository
        name: gitops
  interval: 50m
  values:
    replicaCount: 2
    ingress:
      enabled: true
      className: nginx
