apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: fake
  namespace: fake
spec:
  releaseName: fake
  chart:
    spec:
      chart: ./helm-chart
      sourceRef:
        kind: GitRepository
        name: fake
  interval: 5m
  values:
    replicaCount: 2
    ingress:
      enabled: true
      className: nginx
