apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: fake
  namespace: fake
spec:
  chart:
    spec:
      version: "=0.0.4"
  values:
    ingress:
      hosts:
        - host: fake.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
