apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/chart-for-gitops
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
  - path: chart-for-gitops-values.yaml
    target:
      kind: HelmRelease
